# Generated by Django 4.0.1 on 2022-01-20 06:31

from django.db import migrations, models
import subscriptions.validators


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Submit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('phone_num', models.IntegerField(max_length=50, validators=[subscriptions.validators.validate_symbol])),
                ('agency', models.CharField(choices=[('KT', 'KT'), ('SKT', 'SKT'), ('LG U+', 'LG U+'), ('기타', '기타')], default='통신사', max_length=50)),
                ('equipment', models.CharField(choices=[('Z 플립3', 'Z 플립3'), ('Z 폴드3', 'Z 폴드3'), ('S21', 'S21'), ('S21 Plus', 'S21 Plus'), ('S21 Ultra', 'S21 Ultra')], default='희망 기종', max_length=50)),
                ('pub_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Request',
        ),
    ]
