# Generated by Django 3.2.9 on 2022-01-08 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('phone_num', models.CharField(max_length=50)),
                ('agency', models.CharField(choices=[('KT', 'KT'), ('SKT', 'SKT'), ('LG U+', 'LG U+'), ('기타', '기타')], default='통신사', max_length=50)),
                ('equipment', models.CharField(choices=[('Z 플립3', 'Z 플립3'), ('Z 폴드3', 'Z 폴드3'), ('S21', 'S21'), ('S21 Plus', 'S21 Plus'), ('S21 Ultra', 'S21 Ultra')], default='희망 기종', max_length=50)),
                ('pub_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
